package frc.robot.subsystems;

import java.util.Optional;
import java.util.function.Consumer;
import java.util.function.Supplier;

import org.littletonrobotics.junction.Logger;

import com.ctre.phoenix6.Utils;
import com.ctre.phoenix6.hardware.CANcoder;
import com.ctre.phoenix6.hardware.TalonFX;
import com.ctre.phoenix6.swerve.SwerveDrivetrain;
import com.ctre.phoenix6.swerve.SwerveDrivetrainConstants;
import com.ctre.phoenix6.swerve.SwerveModule;
import com.ctre.phoenix6.swerve.SwerveModuleConstants;
import com.ctre.phoenix6.swerve.SwerveRequest;
import com.pathplanner.lib.auto.AutoBuilder;
import com.pathplanner.lib.config.PIDConstants;
import com.pathplanner.lib.config.RobotConfig;
import com.pathplanner.lib.controllers.PPHolonomicDriveController;

import edu.wpi.first.math.Matrix;
import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.math.geometry.Translation2d;
import edu.wpi.first.math.kinematics.ChassisSpeeds;
import edu.wpi.first.math.numbers.N1;
import edu.wpi.first.math.numbers.N3;
import edu.wpi.first.networktables.NetworkTable;
import edu.wpi.first.networktables.NetworkTableInstance;
import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.Notifier;
import edu.wpi.first.wpilibj.RobotController;
import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj.DriverStation.Alliance;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.Subsystem;
import frc.robot.LimelightHelpers;
import frc.robot.constants.RobotConstants;
import frc.team254.vision.FiducialObservation;
import frc.team254.vision.MegatagPoseEstimate;
import frc.team254.vision.VisionFieldPoseEstimate;
import frc.team254.vision.VisionProcessor;

/**
 * Class that extends the Phoenix 6 SwerveDrivetrain class and implements
 * Subsystem so it can easily be used in command-based projects.
 *
 * Generated by the 2026 Tuner X Swerve Project Generator
 * https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
 */
public class Drivetrain extends SwerveDrivetrain<TalonFX, TalonFX, CANcoder> implements Subsystem {
    private static final double kSimLoopPeriod = 0.004; // 4 ms
    private Notifier m_simNotifier = null;
    private double m_lastSimTime;

    /* Blue alliance sees forward as 0 degrees (toward red alliance wall) */
    private static final Rotation2d kBlueAlliancePerspectiveRotation = Rotation2d.kZero;
    /* Red alliance sees forward as 180 degrees (toward blue alliance wall) */
    private static final Rotation2d kRedAlliancePerspectiveRotation = Rotation2d.k180deg;
    /* Keep track if we've ever applied the operator perspective before or not */
    private boolean m_hasAppliedOperatorPerspective = false;

    private static final Pose2d blueHubPose = new Pose2d(4.626, 4.035, new Rotation2d());
    private static final Pose2d redHubPose = new Pose2d(11.914, 4.035, new Rotation2d());

    private static final Pose2d bluePassShotHighPose = new Pose2d(5.2, 5.1, new Rotation2d());
    private static final Pose2d bluePassShotLowPose = new Pose2d(5.2, 2.9, new Rotation2d());

    private static final Pose2d redPassShotHighPose = new Pose2d(11.4, 5.1, new Rotation2d());
    private static final Pose2d redPassShotLowPose = new Pose2d(11.4, 2.9, new Rotation2d());

    NetworkTable turretCameraTable = NetworkTableInstance.getDefault().getTable("limelight-turret");
    NetworkTable leftCameraTable = NetworkTableInstance.getDefault().getTable("limelight-left");
    NetworkTable rightCameraTable = NetworkTableInstance.getDefault().getTable("limelight-right");

    public final NetworkTableInstance vision = NetworkTableInstance.getDefault();

    public final NetworkTable visionControlTable = vision.getTable("VisionControl");

    public final Consumer<VisionFieldPoseEstimate> visionEstimateConsumer = new Consumer<>() {
        @Override
        public void accept(VisionFieldPoseEstimate visionFieldPoseEstimate) {
            addVisionMeasurement(visionFieldPoseEstimate);
            return;
        }
    };

    VisionProcessor visionProcessor = new VisionProcessor(visionEstimateConsumer);

    public final SwerveRequest.ApplyRobotSpeeds m_pathApplyRobotSpeeds = new SwerveRequest.ApplyRobotSpeeds()
            .withDriveRequestType(SwerveModule.DriveRequestType.Velocity)
            .withSteerRequestType(SwerveModule.SteerRequestType.Position);

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not
     * construct
     * the devices themselves. If they need the devices, they can access them
     * through
     * getters in the classes.
     *
     * @param drivetrainConstants Drivetrain-wide constants for the swerve drive
     * @param modules             Constants for each specific module
     */
    public Drivetrain(
            SwerveDrivetrainConstants drivetrainConstants,
            SwerveModuleConstants<?, ?, ?>... modules) {
         super(
                TalonFX::new, TalonFX::new, CANcoder::new,
                drivetrainConstants, modules
            );
            ConfigureAutobuilder();
    }

    /**
     * Returns a command that applies the specified control request to this swerve
     * drivetrain.
     *
     * @param request Function returning the request to apply
     * @return Command to run
     */
    public Command applyRequest(Supplier<SwerveRequest> request) {
        return run(() -> this.setControl(request.get()));
    }

    public void addVisionMeasurement(VisionFieldPoseEstimate visionFieldPoseEstimate) {
        if (visionFieldPoseEstimate.getVisionMeasurementStdDevs() == null) {
            super.addVisionMeasurement(
                    visionFieldPoseEstimate.getVisionRobotPoseMeters(),
                    Utils.fpgaToCurrentTime(visionFieldPoseEstimate.getTimestampSeconds()));
        } else {
            super.addVisionMeasurement(
                    visionFieldPoseEstimate.getVisionRobotPoseMeters(),
                    Utils.fpgaToCurrentTime(visionFieldPoseEstimate.getTimestampSeconds()),
                    visionFieldPoseEstimate.getVisionMeasurementStdDevs());
        }
    }

    public void periodic() {

        visionPeriodic();

        Logger.recordOutput("Autoaim/DistanceToHub", this.getDistanceToHub());

        Logger.recordOutput("Drivetrain/DriveMotorRotations", this.getModule(1).getDriveMotor().getPosition().getValueAsDouble());
        Logger.recordOutput("Drivetrain/DriveMotorVelocity", this.getModule(1).getDriveMotor().getVelocity().getValueAsDouble());

        /*
         * // * Periodically try to apply the operator perspective.
         * // * If we haven't applied the operator perspective before, then we should
         * apply it regardless of DS state.
         * // * This allows us to correct the perspective in case the robot code
         * restarts mid-match.
         * // * Otherwise, only check and apply the operator perspective if the DS is
         * disabled.
         * // * This ensures driving behavior doesn't change until an explicit disable
         * event occurs during testing.
         * //
         */
        if (!m_hasAppliedOperatorPerspective || DriverStation.isDisabled()) {
            DriverStation.getAlliance().ifPresent(allianceColor -> {
                setOperatorPerspectiveForward(
                allianceColor == Alliance.Red
                ? kRedAlliancePerspectiveRotation
                : kBlueAlliancePerspectiveRotation
                );
                m_hasAppliedOperatorPerspective = true;
            });
        }
    }

    private void startSimThread() {
        m_lastSimTime = Utils.getCurrentTimeSeconds();

        /* Run simulation at a faster rate so PID gains behave more reasonably */
        m_simNotifier = new Notifier(() -> {
            final double currentTime = Utils.getCurrentTimeSeconds();
            double deltaTime = currentTime - m_lastSimTime;
            m_lastSimTime = currentTime;

            /* use the measured time delta, get battery voltage from WPILib */
            updateSimState(deltaTime, RobotController.getBatteryVoltage());
        });
        m_simNotifier.startPeriodic(kSimLoopPeriod);
    }

    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the
     * odometry pose estimate
     * while still accounting for measurement noise.
     *
     * @param visionRobotPoseMeters The pose of the robot as measured by the vision
     *                              camera.
     * @param timestampSeconds      The timestamp of the vision measurement in
     *                              seconds.
     */
    @Override
    public void addVisionMeasurement(Pose2d visionRobotPoseMeters, double timestampSeconds) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds));
    }

    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the
     * odometry pose estimate
     * while still accounting for measurement noise.
     * <p>
     * Note that the vision measurement standard deviations passed into this method
     * will continue to apply to future measurements until a subsequent call to
     * {@link #setVisionMeasurementStdDevs(Matrix)} or this method.
     *
     * @param visionRobotPoseMeters    The pose of the robot as measured by the
     *                                 vision camera.
     * @param timestampSeconds         The timestamp of the vision measurement in
     *                                 seconds.
     * @param visionMeasurementStdDevs Standard deviations of the vision pose
     *                                 measurement
     *                                 in the form [x, y, theta]ᵀ, with units in
     *                                 meters and radians.
     */
    @Override
    public void addVisionMeasurement(
            Pose2d visionRobotPoseMeters,
            double timestampSeconds,
            Matrix<N3, N1> visionMeasurementStdDevs) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds),
                visionMeasurementStdDevs);
    }

    /**
     * Return the pose at a given timestamp, if the buffer is not empty.
     *
     * @param timestampSeconds The timestamp of the pose in seconds.
     * @return The pose at the given timestamp (or Optional.empty() if the buffer is
     *         empty).
     */
    @Override
    public Optional<Pose2d> samplePoseAt(double timestampSeconds) {
        return super.samplePoseAt(Utils.fpgaToCurrentTime(timestampSeconds));
    }

    public void ConfigureAutobuilder() {
        try {
            var config = RobotConfig.fromGUISettings();
            AutoBuilder.configure(
                () -> getState().Pose,   // Supplier of current robot pose
                this::resetPose,         // Consumer for seeding pose against auto
                () -> getState().Speeds, // Supplier of current robot speeds
                // Consumer of ChassisSpeeds and feedforwards to drive the robot
                (speeds, feedforwards) -> setControl(
                    m_pathApplyRobotSpeeds.withSpeeds(ChassisSpeeds.discretize(speeds, 0.020))
                        .withWheelForceFeedforwardsX(feedforwards.robotRelativeForcesXNewtons())
                        .withWheelForceFeedforwardsY(feedforwards.robotRelativeForcesYNewtons())
                ),
                new PPHolonomicDriveController(
                    // PID constants for translation
                    new PIDConstants(10, 0, 0),
                    // PID constants for rotation
                    new PIDConstants(7, 0, 0)
                ),
                config,
                // Assume the path needs to be flipped for Red vs Blue, this is normally the case
                () -> DriverStation.getAlliance().orElse(Alliance.Blue) == Alliance.Red,
                this // Subsystem for requirements
            );
        } catch (Exception ex) {
            DriverStation.reportError("Failed to load PathPlanner config and configure AutoBuilder", ex.getStackTrace());
        }
    }

    public Rotation2d getAngleToPass() {
        if (this.getState().Pose.getY() < 3.2 || this.getState().Pose.getY() > 4.8) {
            if (RobotConstants.isRedAlliance.getAsBoolean()) {
                return this.getState().Pose.getRotation().unaryMinus();
            } else {
                return this.getState().Pose.getRotation().minus(Rotation2d.k180deg).unaryMinus();
            }
        } else {
            if (this.getState().Pose.getY() > 4) {
                if (RobotConstants.isRedAlliance.getAsBoolean()) {
                    return new Rotation2d(
                        Math.atan2(redPassShotHighPose.getY() - this.getState().Pose.getY(), redPassShotHighPose.getX() - this.getState().Pose.getX())
                    ).minus(this.getState().Pose.getRotation());
                } else {
                    return new Rotation2d(
                        Math.atan2(bluePassShotHighPose.getY() - this.getState().Pose.getY(), bluePassShotHighPose.getX() - this.getState().Pose.getX())
                    ).minus(this.getState().Pose.getRotation());
                }
            } else {
                if (RobotConstants.isRedAlliance.getAsBoolean()) {
                    return new Rotation2d(
                        Math.atan2(redPassShotLowPose.getY() - this.getState().Pose.getY(), redPassShotLowPose.getX() - this.getState().Pose.getX())
                    ).minus(this.getState().Pose.getRotation());
                } else {
                    return new Rotation2d(
                        Math.atan2(bluePassShotLowPose.getY() - this.getState().Pose.getY(), bluePassShotLowPose.getX() - this.getState().Pose.getX())
                    ).minus(this.getState().Pose.getRotation());
                }
            }
        }
    }

    public Rotation2d getAngleToScoreWhileMoving(double timeOfFlight) {
        ChassisSpeeds fieldRelativeSpeeds = ChassisSpeeds.fromRobotRelativeSpeeds(
                this.getState().Speeds, this.getState().Pose.getRotation());

        Translation2d robotTranslationOverTime = new Translation2d(
                fieldRelativeSpeeds.vxMetersPerSecond * timeOfFlight,
                fieldRelativeSpeeds.vyMetersPerSecond * timeOfFlight);

        Rotation2d robotToHubAngle;

        if (RobotConstants.isRedAlliance.getAsBoolean()) {
            robotToHubAngle = new Rotation2d(
                    Math.atan2(
                            redHubPose.getY() - robotTranslationOverTime.getY() - this.getState().Pose.getY(),
                            redHubPose.getX() - robotTranslationOverTime.getX() - this.getState().Pose.getX()));
        } else {
            robotToHubAngle = new Rotation2d(
                    Math.atan2(
                            blueHubPose.getY() - robotTranslationOverTime.getY() - this.getState().Pose.getY(),
                            blueHubPose.getX() - robotTranslationOverTime.getX() - this.getState().Pose.getX()));
        }

        Rotation2d turretToHubAngle = robotToHubAngle.minus(this.getState().Pose.getRotation());

        return turretToHubAngle.minus(new Rotation2d(fieldRelativeSpeeds.omegaRadiansPerSecond * 0.1));
    }

    public double getDistanceToHub() {

        if (RobotConstants.isRedAlliance.getAsBoolean()) {
            return getDistanceBetweenPoses(this.getState().Pose, redHubPose);
        } else {
            return getDistanceBetweenPoses(this.getState().Pose, blueHubPose);
        }
    }

    public double getDistanceToHubWhileMoving(double timeOfFlight) {

        ChassisSpeeds fieldRelativeSpeeds = ChassisSpeeds.fromRobotRelativeSpeeds(
                this.getState().Speeds, this.getState().Pose.getRotation());

        Translation2d robotTranslationOverTime = new Translation2d(
                fieldRelativeSpeeds.vxMetersPerSecond * timeOfFlight,
                fieldRelativeSpeeds.vyMetersPerSecond * timeOfFlight);

        if (RobotConstants.isRedAlliance.getAsBoolean()) {
            return getDistanceBetweenPoses(
                    new Pose2d(redHubPose.getTranslation().minus(robotTranslationOverTime), new Rotation2d()),
                    this.getState().Pose);
        } else {
            return getDistanceBetweenPoses(
                    new Pose2d(blueHubPose.getTranslation().minus(robotTranslationOverTime), new Rotation2d()),
                    this.getState().Pose);
        }
    }

    public double getDistanceToDriverStationWall() {

        double fieldLength = 16.54175; 

        if (!RobotConstants.isRedAlliance.getAsBoolean()) {
            return this.getState().Pose.getX(); 
        } else {
            return fieldLength - this.getState().Pose.getX(); 
        }
    }

    public static double getDistanceBetweenPoses(Pose2d pose1, Pose2d pose2) {
        return Math.sqrt(
                ((Math.abs(pose1.getX() - pose2.getX())) * (Math.abs(pose1.getX() - pose2.getX()))) +
                        ((Math.abs(pose1.getY() - pose2.getY())) * (Math.abs(pose1.getY() - pose2.getY()))));
    }

    public static double getDistanceBetweenTranslations(Translation2d translation1, Translation2d translation2) {
        return Math.sqrt(
                ((Math.abs(translation1.getX() - translation2.getX())) * (Math.abs(translation1.getX() - translation2.getX()))) +
                        ((Math.abs(translation1.getY() - translation2.getY())) * (Math.abs(translation1.getY() - translation2.getY()))));
    }

    public static Rotation2d wrapTo2Pi(Rotation2d angle) {
        return new Rotation2d(((angle.getRadians() % (2.0 * Math.PI)) + (2.0 * Math.PI)) % (2.0 * Math.PI));
    }

    public void visionPeriodic() {
        setLLSettings();

        double timestamp = Timer.getTimestamp();
        visionProcessor.driveYawAngularVelocity.addSample(timestamp, this.getState().Speeds.omegaRadiansPerSecond);
        visionProcessor.measuredRobotRelativeChassisSpeeds.set(this.getState().Speeds);
        visionProcessor.robotPose.addSample(timestamp, this.getState().Pose);
        
        boolean leftCameraSeesTarget = leftCameraTable.getEntry("tv").getDouble(0) == 1.0;
        Logger.recordOutput("Drivetrain/leftCameraSeesTarget", leftCameraSeesTarget);
        if (leftCameraSeesTarget) { // does it see target?
            var megatag = LimelightHelpers.getBotPoseEstimate_wpiBlue("limelight-left");
            var megatag2 = LimelightHelpers.getBotPoseEstimate_wpiBlue_MegaTag2("limelight-left");
            Logger.recordOutput("Drivetrain/megatag1llposeLeft", megatag.pose);
            Logger.recordOutput("Drivetrain/megatag2llposeLeft", megatag2.pose);
            if (megatag != null && megatag2 != null){
                visionProcessor.updateVision(
                    leftCameraSeesTarget,
                    FiducialObservation.fromLimelight(megatag.rawFiducials),
                    MegatagPoseEstimate.fromLimelight(megatag),
                    MegatagPoseEstimate.fromLimelight(megatag2),
                    "Vision/left");
            }
        }
        boolean rightCameraSeesTarget = rightCameraTable.getEntry("tv").getDouble(0) == 1.0;
        Logger.recordOutput("Drivetrain/rightCameraSeesTarget", rightCameraSeesTarget);
        if (rightCameraSeesTarget) { // does it see target?
            var megatag = LimelightHelpers.getBotPoseEstimate_wpiBlue("limelight-right");
            var megatag2 = LimelightHelpers.getBotPoseEstimate_wpiBlue_MegaTag2("limelight-right");
            Logger.recordOutput("Drivetrain/megatag1llposeRight", megatag.pose);
            Logger.recordOutput("Drivetrain/megatag2llposeRight", megatag2.pose);
            if (megatag != null && megatag2 != null){
                visionProcessor.updateVision(
                    rightCameraSeesTarget,
                    FiducialObservation.fromLimelight(megatag.rawFiducials),
                    MegatagPoseEstimate.fromLimelight(megatag),
                    MegatagPoseEstimate.fromLimelight(megatag2),
                    "Vision/right");
            }
        }
    }

    private void setLLSettings() {
        
        try {
            LimelightHelpers.SetIMUMode("limelight-right", 1);
            LimelightHelpers.SetIMUMode("limelight-left", 1);

            LimelightHelpers.setCameraPose_RobotSpace("limelight-left", 
                0, 
                -0.305, 
                0.53467, 
                0, 
                0, 
                90);

            LimelightHelpers.setCameraPose_RobotSpace("limelight-right", 
                0, 
                0.305, 
                0.53467, 
                0, 
                0, 
                270);

        } catch (Exception e) {
            Logger.recordOutput("Drivetrain/llsettingsSet", false);
            return;
        }
        Logger.recordOutput("Drivetrain/llsettingsSet", true);
    }
}